name: Java CI with Maven and jpackage

# 触发条件：当一个以 "v" 开头的标签 (如 v1.0, v1.1.0) 被推送到仓库时
on:
  push:
    tags:
      - 'v*'

jobs:
  # --- Windows 构建任务 ---
  build-windows:
    runs-on: windows-latest # 使用最新的Windows虚拟机
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # 1. 下载代码

      - name: Set up JDK 21
        uses: actions/setup-java@v4 # 2. 安装Java 17
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml # 3. 用Maven打包成JAR

      - name: Run jpackage for Windows
        run: |
          jpackage --name "FlywheelCalculator" `
                   --input target/ `
                   --main-jar flywheel-calculator-1.0.0.jar `
                   --main-class com.bear27570.flywheelcalculator.MainApp `
                   --type exe `
                   --dest build/ `
                   --icon packaging/icon.ico `
                   --app-version ${{ github.ref_name }} `
                   --win-console `
                   --java-options "-Dfile.encoding=UTF-8" # 确保中文字符正确

      - name: Upload Windows Installer
        uses: actions/upload-artifact@v4 # 4. 上传构建好的.exe
        with:
          name: Windows-Installer
          path: build/FlywheelCalculator/FlywheelCalculator.exe

  # --- macOS 构建任务 ---
  build-macos:
    runs-on: macos-latest # 使用最新的macOS虚拟机
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run jpackage for macOS
        run: |
          jpackage --name "FlywheelCalculator" \
                   --input target/ \
                   --main-jar flywheel-calculator-1.0.0.jar \
                   --main-class com.bear27570.flywheelcalculator.MainApp \
                   --type dmg \
                   --dest build/ \
                   --icon packaging/icon.icns \
                   --app-version ${{ github.ref_name }} \
                   --java-options "-Dfile.encoding=UTF-8"

      - name: Upload macOS Installer
        uses: actions/upload-artifact@v4
        with:
          name: macOS-Installer
          path: build/FlywheelCalculator.dmg