name: Java CI with Maven and jpackage

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          # 动态设置版本号，并打包
          mvn versions:set -DnewVersion=${{ github.ref_name }}
          mvn -B package --file pom.xml
          # 动态获取生成的JAR文件名
          echo "JAR_NAME=$(ls target/*.jar | xargs -n 1 basename)" >> $GITHUB_ENV
        shell: bash

      - name: Prepare App Version
        # ！！！关键修复 1：
        # 创建一个新的环境变量 APP_VERSION，它的值是 git 标签名去掉了开头的 "v"
        run: echo "APP_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        shell: bash

      - name: Display Info (for debugging)
        run: |
          echo "Git Tag: ${{ github.ref_name }}"
          echo "App Version for jpackage: ${{ env.APP_VERSION }}"
          echo "The built jar is: ${{ env.JAR_NAME }}"
        shell: bash

      # --- Windows 打包步骤 ---
      - name: Run jpackage for Windows
        if: runner.os == 'Windows'
        run: |
          jpackage --name "FlywheelCalculator" `
                   --input target/ `
                   --main-jar ${{ env.JAR_NAME }} `
                   --main-class com.bear27570.flywheelcalculator.MainApp `
                   --type exe `
                   --dest build/ `
                   --icon packaging/icon.ico `
                   --app-version ${{ env.APP_VERSION }} ` # <-- 使用修复后的版本号
                   --win-console `
                   --java-options "-Dfile.encoding=UTF-8"

      # --- macOS 打包步骤 ---
      - name: Run jpackage for macOS
        if: runner.os == 'macOS'
        run: |
          jpackage --name "FlywheelCalculator" \
                   --input target/ \
                   --main-jar ${{ env.JAR_NAME }} \
                   --main-class com.bear27570.flywheelcalculator.MainApp \
                   --type dmg \
                   --dest build/ \
                   --icon packaging/icon.icns \
                   --app-version ${{ env.APP_VERSION }} \ # <-- 使用修复后的版本号
                   --java-options "-Dfile.encoding=UTF-8"

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-Installer
          path: |
            build/FlywheelCalculator.dmg
            build/FlywheelCalculator-*.exe # 使用通配符以匹配Windows下的文件名
          if-no-files-found: error