name: Java CI with Maven and jpackage

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: |
          mvn versions:set -DnewVersion=${{ github.ref_name }}
          mvn -B package --file pom.xml
          echo "JAR_NAME=$(ls target/*.jar | xargs -n 1 basename)" >> $GITHUB_ENV
        shell: bash

      - name: Prepare App Version
        run: echo "APP_VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
        shell: bash

      - name: Verify JAR file exists
        run: |
          if [ ! -f "target/${{ env.JAR_NAME }}" ]; then
            echo "::error::JAR file not found at target/${{ env.JAR_NAME }}"
            exit 1
          fi
          echo "JAR file found."
        shell: bash

      - name: Run jpackage for Windows
        if: runner.os == 'Windows'
        run: >
          jpackage
          --name "FlywheelCalculator" --input target/ --main-jar ${{ env.JAR_NAME }}
          --main-class com.bear27570.flywheelcalculator.MainApp
          --type exe --dest build/ --icon packaging/icon.ico
          --app-version ${{ env.APP_VERSION }} --win-console
          --java-options "-Dfile.encoding=UTF-8"

      - name: Run jpackage for macOS
        if: runner.os == 'macOS'
        run: >
          jpackage
          --name "FlywheelCalculator" --input target/ --main-jar ${{ env.JAR_NAME }}
          --main-class com.bear27570.flywheelcalculator.MainApp
          --type dmg --dest build/ --icon packaging/icon.icns
          --app-version ${{ env.APP_VERSION }}
          --java-options "-Dfile.encoding=UTF-8"

      # ！！！关键修复 1：增加一个调试步骤来查看生成的文件 ！！！
      - name: List build directory contents (for debugging)
        run: |
          echo "Listing contents of the 'build' directory..."
          ls -R build
        shell: bash

      - name: Upload Installer
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-Installer-${{ env.APP_VERSION }}
          # ！！！关键修复 2：修正 Windows 的文件路径 ！！！
          # jpackage for Windows creates a sub-directory with the app name.
          path: |
            build/FlywheelCalculator.dmg
            build/FlywheelCalculator/FlywheelCalculator.exe
          if-no-files-found: error